[build-system]
requires = ["packaging>=22", "tomli; python_version<'3.11'"]
build-backend = "pymonorepo.backend"
backend-path = ["../build/src"]

[project]
name = "pymonorepo-cli"
dynamic = [
    "version",
    "description",
]
authors = [{name = "Chris Sewell", email = "chrisj_sewell@hotmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "build >=0.9",
    "click >=8",
    "pyyaml >=6",
    "pymonorepo",
]
requires-python = ">=3.7"

[project.scripts]
pmr = "pymonorepo_cli:__main__"
