[build-system]
requires = ["packaging>=22", "tomli"]
build-backend = "pymonorepo.backend"
backend-path = ["src"]

[project]
name = "pymonorepo"
dynamic = [
    "version",
    "description",
]
authors = [{name = "Chris Sewell", email = "chrisj_sewell@hotmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License"
]
dependencies = ["packaging>=22", "tomli"]
requires-python = ">=3.7"

[project.urls]
Home = "https://github.com/chrisjsewell/pymonorepo"

[tool.monorepo.package]
module = "src/pymonorepo"
about = "src/pymonorepo/__init__.py"
